template = "https://github.com/giellalt/template-lang-und"
rev_id = 302
template_sha = "b3740681672fe3b348eb75d3170f7a2da900a0b1"

[replacements]
__GLOTTOLOG_ID__ = "nucl1301"
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
