template = "https://github.com/giellalt/template-lang-und"
rev_id = 345
template_sha = "f04ff6c72fd325cdfed0bbaee815bd2f43d847a7"

[replacements]
__GLOTTOLOG_ID__ = "nucl1301"
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
