template = "https://github.com/giellalt/template-lang-und"
rev_id = 328
template_sha = "a66ce6606ea33e46cd3439c88cafa44d4dcdde92"

[replacements]
__GLOTTOLOG_ID__ = "nucl1301"
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
